version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=medyczne
      - POSTGRES_USER=medyczne
      - POSTGRES_PASSWORD=medyczne123
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db