# Generated by Django 4.0.1 on 2022-01-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apteka', '0002_producent_alter_apteka_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apteka',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apteka.producent'),
        ),
    ]
