# Generated by Django 3.2.9 on 2022-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apteka', '0004_kategoria_apteka_kategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrazy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField(blank=True)),
                ('obraz', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Obraz',
                'verbose_name_plural': 'Obrazy',
            },
        ),
        migrations.AddField(
            model_name='apteka',
            name='obraz',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
