# Generated by Django 3.2.9 on 2022-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apteka', '0005_auto_20220125_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apteka',
            name='obraz',
            field=models.ImageField(default=True, upload_to='obrazy/'),
        ),
    ]
