# Generated by Django 3.2.9 on 2022-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apteka', '0006_alter_apteka_obraz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField()),
                ('nabyto', models.BooleanField(default=False)),
                ('komu_zapisano', models.TextField()),
            ],
            options={
                'verbose_name': 'Recepta',
                'verbose_name_plural': 'Recepty',
            },
        ),
    ]
